/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: saferide.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _SAFERIDE_H_
#define _SAFERIDE_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef saferide__ns
#define saferide__ns 2056189222
#define saferide__ns_id "http://saferide.io/ns/saferide"
#define saferide__ns_uri "http://saferide.io/ns/saferide"
#endif

#define saferide_rule 661146188
#define saferide_log_facility 53513673
#define saferide_dstport 196197344
#define saferide_srcaddr 1903025035
#define saferide_name 1998270519
#define saferide_can 1769100362
#define saferide_action 571883887
#define saferide_dstnetmask 1653301185
#define saferide_permission 2123252186
#define saferide_net 872020178
#define saferide_config 2105663071
#define saferide_proto 1902903574
#define saferide_program 375362655
#define saferide_file 867066344
#define saferide_ip 1643785435
#define saferide_id 1279252765
#define saferide_terminate 625613193
#define saferide_black_list 862062469
#define saferide_tuple 958203093
#define saferide_dstaddr 1617334360
#define saferide_vsentry 452359654
#define saferide_log 1285913844
#define saferide_list_actions 1825198973
#define saferide_user 1529217067
#define saferide_num 1089485166
#define saferide_srcnetmask 2120899153
#define saferide_sr_actions 779968891
#define saferide_system 1534086422
#define saferide_engine 1355267631
#define saferide_msg_id 433328536
#define saferide_max_rate 842809007
#define saferide_log_severity 1750958879
#define saferide_control 573205060
#define saferide_srcport 1110521831

#ifdef __cplusplus
}
#endif

#endif
